import "@workspace/ui/globals.css";
import { type Metadata } from "next";
import { Roboto } from "next/font/google";
const fontRoboto = Roboto({
  subsets: ["latin", "latin-ext"],
  weight: ["100", "300", "400", "500", "700", "900"],
  variable: "--font-roboto",
});
export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default async function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={fontRoboto.className} suppressHydrationWarning>
      <body>{children}</body>
    </html>
  );
}
