import "@workspace/ui/globals.css";
import { type Metadata } from "next";
// import {Roboto} from "next/font/google"

import { Providers } from "../components/providerWrapper";
import Header from "@/components/Header/Header";
import { AppSidebar} from "@/components/app-sidebar";
import { SidebarInset, SidebarProvider } from "@workspace/ui/components/sidebar";

// const fontSans = Geist({
//   subsets: ["latin"],
//   variable: "--font-sans",
// });

// const fontMono = Geist_Mono({
//   subsets: ["latin"],
//   variable: "--font-mono",
// });

// const fontRoboto = Roboto({
//   subsets: ["latin","latin-ext"],
//   weight: ["100", "300","400","500","700","900"],
//   variable: "--font-roboto",
// })
export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={``} suppressHydrationWarning>
      <body>
        <Providers
        >

          <div className="flex flex-col min-h-screen">
          <SidebarProvider >
            <AppSidebar />
          <div className="flex flex-1">
            {/* <Sidebar /> */}
            <SidebarInset>

          <Header />
            <main className="">{children}</main>
            </SidebarInset>
          </div>
          </SidebarProvider>
        </div>
        </Providers>
      </body>
    </html>
  );
}
